core/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("home.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("resume/", include("resume.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resume/urls.py
from django.urls import path
from .views import ResumeInformationView, ResumeRetrieveAPIView, ResumeRetriveView

app_name = "resume"
urlpatterns = [
    path("create/", ResumeInformationView.as_view(), name="resume-information"),
    path("view/<uuid:pk>/", ResumeRetriveView.as_view(), name="resume-view"),
    path("<uuid:pk>/", ResumeRetrieveAPIView.as_view(), name="resume-view-api"),
    
    # path("create/information/", resumeInformationView, name="information-create"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        {% block style %}
        {% endblock style %}

        {% block script %}
        {% endblock script %}

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
    <body>
        salom header <br><br><br><hr><br><br>
        {% block content %}
        {% endblock content %}
    </body>
    <script src="{% static 'js/resume1.js' %}"></script>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
Resume Create home
{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'resume:resume-information' %}">Create Resume</a></p>
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}

{% endblock content %}

templates/resume-base.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Resume review page
{% endblock title %}